In [2]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [3]:
my_arr = np.arange(1000000)

In [4]:
my_list = list(range(1000000))

In [104]:
%time for in range(10): my_arr2 = my_arr * 2 
CPU_times: user 20 ms, sys: 50 ms, total: 70 ms
Wall_time: 72.4 ms

SyntaxError: invalid syntax (<ipython-input-104-86d59a148808>, line 2)

In [13]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list] CPU times: user 760 ms, sys: 290 ms, total: 1.05 s
Wall time: 1.05 s

SyntaxError: invalid syntax (<ipython-input-13-4e3c1f338306>, line 2)

# 4.1 The NumPy ndarray: A Multidimensional Array Object

In [14]:
data = np.random.randn(2, 3)


In [15]:
data

array([[ 0.5410888 ,  0.20139192, -1.18014284],
       [-0.07794223,  0.06570018, -0.83863925]])

In [16]:
data * 10

array([[  5.41088801,   2.01391915, -11.80142838],
       [ -0.77942234,   0.65700179,  -8.38639246]])

In [17]:
data + data

array([[ 1.0821776 ,  0.40278383, -2.36028568],
       [-0.15588447,  0.13140036, -1.67727849]])

In [18]:
data.shape

(2, 3)

In [19]:
data.dtype

dtype('float64')

In [20]:
data1 = [6, 7.5, 8, 0, 1]

In [21]:
arr1 = np.array(data1)

In [22]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [23]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [24]:
arr2 = np.array(data2)

In [25]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
arr2.ndim

2

In [27]:
arr2.shape

(2, 4)

In [28]:
arr1.dtype

dtype('float64')

In [29]:
arr2.dtype

dtype('int64')

In [30]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
np.empty((2,3,2))

array([[[3.10503618e+231, 3.10503618e+231],
        [2.96439388e-323, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[3.10503618e+231, 3.10503618e+231],
        [8.41319378e+164, 7.49722721e-067],
        [3.99910963e+252, 8.34404819e-309]]])

In [33]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [35]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [36]:
arr1.dtype

dtype('float64')

In [37]:
arr2.dtype

dtype('int32')

In [38]:
arr = np.array([1, 2, 3, 4, 5])

In [39]:
arr.dtype

dtype('int64')

In [40]:
float_arr = arr.astype(np.float64)

In [41]:
float_arr.dtype

dtype('float64')

In [42]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [43]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [44]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [45]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [46]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [47]:
int_array = np.arange(10)

In [48]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [49]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [50]:
empty_uint32 = np.empty(8, dtype='u4')

In [51]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [52]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [53]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [54]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [55]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [56]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [57]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [58]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [59]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [60]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [61]:
arr = np.arange(10)

In [62]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr[5]

5

In [64]:
arr[5:8]

array([5, 6, 7])

In [65]:
arr[5:8] = 12

In [66]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [67]:
arr_slice = arr[5:8]

In [68]:
arr_slice

array([12, 12, 12])

In [69]:
arr_slice[1] = 12345

In [70]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [71]:
arr_slice[:] = 64

In [72]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [73]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [74]:
arr2d[2]

array([7, 8, 9])

In [75]:
arr2d[0][2]

3

In [76]:
arr2d[0, 2]

3

In [77]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [78]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [79]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
old_values = arr3d[0].copy()

In [81]:
arr3d[0] = 42

In [82]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [83]:
arr3d[0] = old_values

In [84]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [85]:
arr3d[1, 0]

array([7, 8, 9])

In [86]:
x = arr3d[1]

In [87]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [88]:
x[0]

array([7, 8, 9])

In [89]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [90]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [91]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [94]:
arr2d[1, :2]

array([4, 5])

In [95]:
arr2d[:2, 2]

array([3, 6])

In [96]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [97]:
arr2d[:2, 1:] = 0

In [98]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [99]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [100]:
data = np.random.randn(7, 4)

In [101]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [102]:
data

array([[ 0.86363857,  0.21271694,  0.02802016,  0.75676825],
       [-0.9958742 ,  0.08356184, -0.53398169, -0.28198592],
       [ 0.2832594 ,  0.22018886,  0.27360288, -0.67982899],
       [-0.23502966, -0.80062073,  0.74405378,  0.59829215],
       [ 0.26227414, -0.33784054, -0.88950943, -0.51888444],
       [-0.67588028,  0.33141151, -0.18855355, -1.3843255 ],
       [ 1.01327547, -0.9930561 ,  1.61612213, -0.38365718]])

In [105]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [106]:
data[names == 'Bob']

array([[ 0.86363857,  0.21271694,  0.02802016,  0.75676825],
       [-0.23502966, -0.80062073,  0.74405378,  0.59829215]])

In [107]:
data[names == 'Bob', 2:]

array([[0.02802016, 0.75676825],
       [0.74405378, 0.59829215]])

In [108]:
data[names == 'Bob', 3]

array([0.75676825, 0.59829215])

In [109]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [110]:
data[~(names == 'Bob')]

array([[-0.9958742 ,  0.08356184, -0.53398169, -0.28198592],
       [ 0.2832594 ,  0.22018886,  0.27360288, -0.67982899],
       [ 0.26227414, -0.33784054, -0.88950943, -0.51888444],
       [-0.67588028,  0.33141151, -0.18855355, -1.3843255 ],
       [ 1.01327547, -0.9930561 ,  1.61612213, -0.38365718]])

In [111]:
cond = names == 'Bob'

In [112]:
data[~cond]

array([[-0.9958742 ,  0.08356184, -0.53398169, -0.28198592],
       [ 0.2832594 ,  0.22018886,  0.27360288, -0.67982899],
       [ 0.26227414, -0.33784054, -0.88950943, -0.51888444],
       [-0.67588028,  0.33141151, -0.18855355, -1.3843255 ],
       [ 1.01327547, -0.9930561 ,  1.61612213, -0.38365718]])

In [113]:
mask = (names == 'Bob') | (names == 'Will')

In [114]:
mask

array([ True, False,  True,  True,  True, False, False])

In [115]:
data[mask]

array([[ 0.86363857,  0.21271694,  0.02802016,  0.75676825],
       [ 0.2832594 ,  0.22018886,  0.27360288, -0.67982899],
       [-0.23502966, -0.80062073,  0.74405378,  0.59829215],
       [ 0.26227414, -0.33784054, -0.88950943, -0.51888444]])

In [116]:
data[data < 0] = 0

In [117]:
data

array([[0.86363857, 0.21271694, 0.02802016, 0.75676825],
       [0.        , 0.08356184, 0.        , 0.        ],
       [0.2832594 , 0.22018886, 0.27360288, 0.        ],
       [0.        , 0.        , 0.74405378, 0.59829215],
       [0.26227414, 0.        , 0.        , 0.        ],
       [0.        , 0.33141151, 0.        , 0.        ],
       [1.01327547, 0.        , 1.61612213, 0.        ]])

In [118]:
data[names != 'Joe'] = 7

In [119]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.08356184, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.33141151, 0.        , 0.        ],
       [1.01327547, 0.        , 1.61612213, 0.        ]])

In [120]:
arr = np.empty((8, 4))

In [121]:
for i in range(8):
    arr[i] = i

In [122]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [123]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [124]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [125]:
arr = np.arange(32).reshape((8, 4))

In [126]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [127]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [128]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [129]:
arr = np.arange(15).reshape((3, 5))

In [130]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [131]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [132]:
arr = np.random.randn(6, 3)

In [133]:
arr

array([[-0.35251219,  0.05942044,  0.31691547],
       [ 0.08266116,  0.82928959,  0.77128724],
       [-0.30293173,  0.61032517, -1.77575344],
       [ 1.3723834 , -0.09300982, -0.04566685],
       [ 0.1054643 , -0.7343038 , -0.52168024],
       [-0.34878697, -0.10448332,  0.60566484]])

In [134]:
np.dot(arr.T, arr)

array([[ 2.23907662, -0.3059288 ,  0.16103191],
       [-0.3059288 ,  1.62251847, -0.10129791],
       [ 0.16103191, -0.10129791,  4.48968533]])

In [135]:
arr = np.arange(16).reshape((2, 2, 4))

In [136]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [137]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [138]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [139]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

# 4.2 Universal Functions: Fast Element-Wise Array Functions

In [140]:
arr = np.arange(10)

In [141]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [143]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [144]:
x = np.random.randn(8)

In [145]:
y = np.random.randn(8)

In [146]:
x

array([ 1.13717985, -1.37263167,  0.48174947, -1.08613733, -0.13961104,
       -0.76346892, -0.53339334, -1.13302101])

In [147]:
y

array([-0.36006315,  0.71900921, -1.18007627,  0.20046881,  0.4095156 ,
       -0.91750819,  1.21712878, -0.23582052])

In [148]:
np.maximum(x, y)

array([ 1.13717985,  0.71900921,  0.48174947,  0.20046881,  0.4095156 ,
       -0.76346892,  1.21712878, -0.23582052])

In [149]:
arr = np.random.randn(7) * 5

In [150]:
arr

array([ 5.01537205, -8.07303741,  8.40750082, -6.72744426,  5.96619493,
       -0.10644436,  4.30976899])

In [151]:
remainder, whole_part = np.modf(arr)

In [152]:
remainder

array([ 0.01537205, -0.07303741,  0.40750082, -0.72744426,  0.96619493,
       -0.10644436,  0.30976899])

In [153]:
whole_part

array([ 5., -8.,  8., -6.,  5., -0.,  4.])

In [154]:
arr

array([ 5.01537205, -8.07303741,  8.40750082, -6.72744426,  5.96619493,
       -0.10644436,  4.30976899])

In [155]:
np.sqrt(arr)

<ipython-input-155-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([2.23950263,        nan, 2.89956907,        nan, 2.44257956,
              nan, 2.07599831])

In [156]:
np.sqrt(arr, arr)

<ipython-input-156-164954cb2c14>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([2.23950263,        nan, 2.89956907,        nan, 2.44257956,
              nan, 2.07599831])